---
extends:
  - plugin:tribou/recommended
  - prettier

plugins:
  - tribou

settings:
  import/resolver: webpack

rules:
  react/jsx-indent:
    - 2
    - tab
  react/jsx-indent-props:
    - 2
    - tab

globals:
  # Global Flow Types
  # https://github.com/babel/babel-eslint/issues/130#issuecomment-111216872
  BuildAssets: false
  CssLoaders: false
