---
extends:
  - plugin:tribou/recommended

plugins:
  - tribou

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: false
  import/resolver: webpack
  import/no-extraneous-dependencies:
    - error
    - packageDir: '../'

globals:
  # Global Flow Types
  # https://github.com/babel/babel-eslint/issues/130#issuecomment-111216872
  BuildAssets: false
  CssLoaders: false
