---
extends:
  - plugin:tribou/recommended

plugins:
  - tribou

settings:
  import/resolver: webpack

globals:
  # Global Flow Types
  # https://github.com/babel/babel-eslint/issues/130#issuecomment-111216872
  BuildAssets: false
  CssLoaders: false
