// flow-typed signature: 8ee85dc788e1822dbf0160bf7a7cc6b2
// flow-typed version: <<STUB>>/boom_v^4.2.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'boom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boom/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boom/lib/index.js' {
  declare module.exports: $Exports<'boom/lib/index'>;
}
