// flow-typed signature: e0c933645b0d625baa77c140a5c5e72a
// flow-typed version: <<STUB>>/cookies-js_v^1.2.3/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cookies-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cookies-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cookies-js/dist/cookies' {
  declare module.exports: any;
}

declare module 'cookies-js/dist/cookies.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cookies-js/dist/cookies.js' {
  declare module.exports: $Exports<'cookies-js/dist/cookies'>;
}
declare module 'cookies-js/dist/cookies.min.js' {
  declare module.exports: $Exports<'cookies-js/dist/cookies.min'>;
}
