// flow-typed signature: dd080ab86e35a7ff68c88431c64a945f
// flow-typed version: <<STUB>>/eslint-config-tribou_v^3.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-tribou'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-tribou' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-tribou/test/component/Home.index' {
  declare module.exports: any;
}

declare module 'eslint-config-tribou/test/component/Home' {
  declare module.exports: any;
}

declare module 'eslint-config-tribou/test/reducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-tribou/index' {
  declare module.exports: $Exports<'eslint-config-tribou'>;
}
declare module 'eslint-config-tribou/index.js' {
  declare module.exports: $Exports<'eslint-config-tribou'>;
}
declare module 'eslint-config-tribou/test/component/Home.index.js' {
  declare module.exports: $Exports<'eslint-config-tribou/test/component/Home.index'>;
}
declare module 'eslint-config-tribou/test/component/Home.js' {
  declare module.exports: $Exports<'eslint-config-tribou/test/component/Home'>;
}
declare module 'eslint-config-tribou/test/reducer.js' {
  declare module.exports: $Exports<'eslint-config-tribou/test/reducer'>;
}
