// flow-typed signature: acacacbbee5b1a5ab9f4e6156573b046
// flow-typed version: <<STUB>>/eslint-plugin-tribou_v^1.0.5/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-tribou'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-tribou' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-tribou/bin/yarn-0.24.6' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/eslint-config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/cross-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/deepmerge_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-config-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-node_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/identity-obj-proxy_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/jest_v20.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/nodemon_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/react-redux_v5.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/test/arrow-body-style_test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/test/arrow-parens_test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/test/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/test/react/Home/Home_test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/test/react/Home/Home.index_test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-tribou/test/redux/reducer_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-tribou/bin/yarn-0.24.6.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/bin/yarn-0.24.6'>;
}
declare module 'eslint-plugin-tribou/eslint-config.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/eslint-config'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/cross-env_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/cross-env_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/deepmerge_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/deepmerge_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-config-standard_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/eslint-config-standard_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-node_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-node_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-promise_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-standard_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/eslint-plugin-standard_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/husky_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/identity-obj-proxy_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/identity-obj-proxy_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/jest_v20.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/jest_v20.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/nodemon_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/nodemon_vx.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/react-redux_v5.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/react-redux_v5.x.x'>;
}
declare module 'eslint-plugin-tribou/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/flow-typed/npm/redux_v3.x.x'>;
}
declare module 'eslint-plugin-tribou/index' {
  declare module.exports: $Exports<'eslint-plugin-tribou'>;
}
declare module 'eslint-plugin-tribou/index.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou'>;
}
declare module 'eslint-plugin-tribou/test/arrow-body-style_test.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/test/arrow-body-style_test'>;
}
declare module 'eslint-plugin-tribou/test/arrow-parens_test.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/test/arrow-parens_test'>;
}
declare module 'eslint-plugin-tribou/test/index.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/test/index'>;
}
declare module 'eslint-plugin-tribou/test/react/Home/Home_test.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/test/react/Home/Home_test'>;
}
declare module 'eslint-plugin-tribou/test/react/Home/Home.index_test.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/test/react/Home/Home.index_test'>;
}
declare module 'eslint-plugin-tribou/test/redux/reducer_test.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou/test/redux/reducer_test'>;
}
