// flow-typed signature: 877079db2134e9340db4d0d29abb8750
// flow-typed version: <<STUB>>/eslint-plugin-tribou_v^2.0.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-tribou'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-tribou' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-plugin-tribou/index' {
  declare module.exports: $Exports<'eslint-plugin-tribou'>;
}
declare module 'eslint-plugin-tribou/index.js' {
  declare module.exports: $Exports<'eslint-plugin-tribou'>;
}
