// flow-typed signature: 23b5e89026fe3d3b794204c0a5b364e7
// flow-typed version: <<STUB>>/fetch-ponyfill_v^4.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-ponyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-ponyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-ponyfill/build/fetch-browser' {
  declare module.exports: any;
}

declare module 'fetch-ponyfill/fetch-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-ponyfill/build/fetch-browser.js' {
  declare module.exports: $Exports<'fetch-ponyfill/build/fetch-browser'>;
}
declare module 'fetch-ponyfill/fetch-node.js' {
  declare module.exports: $Exports<'fetch-ponyfill/fetch-node'>;
}
