// flow-typed signature: 83a7bf2aa16d61b6ff3d3fb847b7f1f2
// flow-typed version: <<STUB>>/good_v^7.2.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'good'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'good' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'good/lib/index' {
  declare module.exports: any;
}

declare module 'good/lib/monitor' {
  declare module.exports: any;
}

declare module 'good/lib/schema' {
  declare module.exports: any;
}

declare module 'good/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'good/lib/index.js' {
  declare module.exports: $Exports<'good/lib/index'>;
}
declare module 'good/lib/monitor.js' {
  declare module.exports: $Exports<'good/lib/monitor'>;
}
declare module 'good/lib/schema.js' {
  declare module.exports: $Exports<'good/lib/schema'>;
}
declare module 'good/lib/utils.js' {
  declare module.exports: $Exports<'good/lib/utils'>;
}
