// flow-typed signature: da917e68c5dd2a6718153721093df4ce
// flow-typed version: <<STUB>>/hapi-react-views_v^10.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hapi-react-views'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hapi-react-views' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hapi-react-views/examples/layout-component/server' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/layout-component/views/about' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/layout-component/views/home' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/layout-component/views/layout' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/layout/server' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/layout/views/about' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/layout/views/home' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/layout/views/layout' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/remount/client' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/remount/components/app' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/remount/components/html' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/remount/server' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/remount/webpack' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/simple/server' {
  declare module.exports: any;
}

declare module 'hapi-react-views/examples/simple/views/home' {
  declare module.exports: any;
}

declare module 'hapi-react-views/test/fixtures/layout-es6' {
  declare module.exports: any;
}

declare module 'hapi-react-views/test/fixtures/layout' {
  declare module.exports: any;
}

declare module 'hapi-react-views/test/fixtures/navbar' {
  declare module.exports: any;
}

declare module 'hapi-react-views/test/fixtures/view-es6' {
  declare module.exports: any;
}

declare module 'hapi-react-views/test/fixtures/view' {
  declare module.exports: any;
}

declare module 'hapi-react-views/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hapi-react-views/examples/layout-component/server.js' {
  declare module.exports: $Exports<'hapi-react-views/examples/layout-component/server'>;
}
declare module 'hapi-react-views/examples/layout-component/views/about.jsx' {
  declare module.exports: $Exports<'hapi-react-views/examples/layout-component/views/about'>;
}
declare module 'hapi-react-views/examples/layout-component/views/home.jsx' {
  declare module.exports: $Exports<'hapi-react-views/examples/layout-component/views/home'>;
}
declare module 'hapi-react-views/examples/layout-component/views/layout.jsx' {
  declare module.exports: $Exports<'hapi-react-views/examples/layout-component/views/layout'>;
}
declare module 'hapi-react-views/examples/layout/server.js' {
  declare module.exports: $Exports<'hapi-react-views/examples/layout/server'>;
}
declare module 'hapi-react-views/examples/layout/views/about.jsx' {
  declare module.exports: $Exports<'hapi-react-views/examples/layout/views/about'>;
}
declare module 'hapi-react-views/examples/layout/views/home.jsx' {
  declare module.exports: $Exports<'hapi-react-views/examples/layout/views/home'>;
}
declare module 'hapi-react-views/examples/layout/views/layout.jsx' {
  declare module.exports: $Exports<'hapi-react-views/examples/layout/views/layout'>;
}
declare module 'hapi-react-views/examples/remount/client.js' {
  declare module.exports: $Exports<'hapi-react-views/examples/remount/client'>;
}
declare module 'hapi-react-views/examples/remount/components/app.jsx' {
  declare module.exports: $Exports<'hapi-react-views/examples/remount/components/app'>;
}
declare module 'hapi-react-views/examples/remount/components/html.jsx' {
  declare module.exports: $Exports<'hapi-react-views/examples/remount/components/html'>;
}
declare module 'hapi-react-views/examples/remount/server.js' {
  declare module.exports: $Exports<'hapi-react-views/examples/remount/server'>;
}
declare module 'hapi-react-views/examples/remount/webpack.js' {
  declare module.exports: $Exports<'hapi-react-views/examples/remount/webpack'>;
}
declare module 'hapi-react-views/examples/simple/server.js' {
  declare module.exports: $Exports<'hapi-react-views/examples/simple/server'>;
}
declare module 'hapi-react-views/examples/simple/views/home.jsx' {
  declare module.exports: $Exports<'hapi-react-views/examples/simple/views/home'>;
}
declare module 'hapi-react-views/index' {
  declare module.exports: $Exports<'hapi-react-views'>;
}
declare module 'hapi-react-views/index.js' {
  declare module.exports: $Exports<'hapi-react-views'>;
}
declare module 'hapi-react-views/test/fixtures/layout-es6.jsx' {
  declare module.exports: $Exports<'hapi-react-views/test/fixtures/layout-es6'>;
}
declare module 'hapi-react-views/test/fixtures/layout.jsx' {
  declare module.exports: $Exports<'hapi-react-views/test/fixtures/layout'>;
}
declare module 'hapi-react-views/test/fixtures/navbar.jsx' {
  declare module.exports: $Exports<'hapi-react-views/test/fixtures/navbar'>;
}
declare module 'hapi-react-views/test/fixtures/view-es6.jsx' {
  declare module.exports: $Exports<'hapi-react-views/test/fixtures/view-es6'>;
}
declare module 'hapi-react-views/test/fixtures/view.jsx' {
  declare module.exports: $Exports<'hapi-react-views/test/fixtures/view'>;
}
declare module 'hapi-react-views/test/index.js' {
  declare module.exports: $Exports<'hapi-react-views/test/index'>;
}
