// flow-typed signature: 5a9f3236609292b7c878a6a352b2f030
// flow-typed version: <<STUB>>/imageoptim-cli_v^1.14.8/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imageoptim-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'imageoptim-cli' {
  declare module.exports: any;
}
