// flow-typed signature: 8668a1250676c3e437973c1b663f1e03
// flow-typed version: <<STUB>>/inert_v^4.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inert/lib/directory' {
  declare module.exports: any;
}

declare module 'inert/lib/etag' {
  declare module.exports: any;
}

declare module 'inert/lib/file' {
  declare module.exports: any;
}

declare module 'inert/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inert/lib/directory.js' {
  declare module.exports: $Exports<'inert/lib/directory'>;
}
declare module 'inert/lib/etag.js' {
  declare module.exports: $Exports<'inert/lib/etag'>;
}
declare module 'inert/lib/file.js' {
  declare module.exports: $Exports<'inert/lib/file'>;
}
declare module 'inert/lib/index.js' {
  declare module.exports: $Exports<'inert/lib/index'>;
}
