// flow-typed signature: c0c9cc7e67cc39de665836fd35df864a
// flow-typed version: <<STUB>>/jest-serializer-path_v^0.1.13/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-serializer-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-serializer-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-serializer-path/lib/index_test' {
  declare module.exports: any;
}

declare module 'jest-serializer-path/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-serializer-path/lib/index_test.js' {
  declare module.exports: $Exports<'jest-serializer-path/lib/index_test'>;
}
declare module 'jest-serializer-path/lib/index.js' {
  declare module.exports: $Exports<'jest-serializer-path/lib/index'>;
}
