// flow-typed signature: 61024604b4bf37e098724b8c1d51c988
// flow-typed version: <<STUB>>/jest-serializer-path_v^0.1.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-serializer-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-serializer-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-serializer-path/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-serializer-path/lib/index.js' {
  declare module.exports: $Exports<'jest-serializer-path/lib/index'>;
}
