// flow-typed signature: 34b89caf73c1af2faa86ba067028484f
// flow-typed version: <<STUB>>/make-promises-safe_v^1.1.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'make-promises-safe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'make-promises-safe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'make-promises-safe/example' {
  declare module.exports: any;
}

declare module 'make-promises-safe/make-promises-safe' {
  declare module.exports: any;
}

declare module 'make-promises-safe/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'make-promises-safe/example.js' {
  declare module.exports: $Exports<'make-promises-safe/example'>;
}
declare module 'make-promises-safe/make-promises-safe.js' {
  declare module.exports: $Exports<'make-promises-safe/make-promises-safe'>;
}
declare module 'make-promises-safe/test.js' {
  declare module.exports: $Exports<'make-promises-safe/test'>;
}
