// flow-typed signature: 924047a3ad630150f9c357e0dc8e9c2b
// flow-typed version: <<STUB>>/node-notifier-cli_v^1.0.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-notifier-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-notifier-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-notifier-cli/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-notifier-cli/bin.js' {
  declare module.exports: $Exports<'node-notifier-cli/bin'>;
}
