// flow-typed signature: c7449b10e6e76daaa6296a1337eb07e0
// flow-typed version: <<STUB>>/postcss-calc_v^5.3.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-calc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-calc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-calc/index' {
  declare module.exports: $Exports<'postcss-calc'>;
}
declare module 'postcss-calc/index.js' {
  declare module.exports: $Exports<'postcss-calc'>;
}
