// flow-typed signature: 5d98e62c8a0158ad5b1b98a8a777383d
// flow-typed version: <<STUB>>/precss_v^2.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'precss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'precss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'precss/index' {
  declare module.exports: $Exports<'precss'>;
}
declare module 'precss/index.js' {
  declare module.exports: $Exports<'precss'>;
}
