// flow-typed signature: aa3c86275434e621224299f052fdbf3c
// flow-typed version: <<STUB>>/react-native-splash-screen_v^3.0.7/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-splash-screen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-splash-screen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-splash-screen/index' {
  declare module.exports: $Exports<'react-native-splash-screen'>;
}
declare module 'react-native-splash-screen/index.js' {
  declare module.exports: $Exports<'react-native-splash-screen'>;
}
