// flow-typed signature: 47721ffa32ca5cd4485c526ef0833ebb
// flow-typed version: <<STUB>>/react-router-native-stack_v^0.0.11/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-native-stack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-native-stack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-native-stack/lib/animationTypes' {
  declare module.exports: any;
}

declare module 'react-router-native-stack/lib/findFirstMatch' {
  declare module.exports: any;
}

declare module 'react-router-native-stack/lib/getDimension' {
  declare module.exports: any;
}

declare module 'react-router-native-stack/lib/getDuration' {
  declare module.exports: any;
}

declare module 'react-router-native-stack/lib/getEasing' {
  declare module.exports: any;
}

declare module 'react-router-native-stack/lib/getTransforms' {
  declare module.exports: any;
}

declare module 'react-router-native-stack/lib/index' {
  declare module.exports: any;
}

declare module 'react-router-native-stack/lib/Stack' {
  declare module.exports: any;
}

declare module 'react-router-native-stack/lib/StackTransitioner' {
  declare module.exports: any;
}

declare module 'react-router-native-stack/lib/styles' {
  declare module.exports: any;
}

declare module 'react-router-native-stack/lib/transitionTypes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-native-stack/lib/animationTypes.js' {
  declare module.exports: $Exports<'react-router-native-stack/lib/animationTypes'>;
}
declare module 'react-router-native-stack/lib/findFirstMatch.js' {
  declare module.exports: $Exports<'react-router-native-stack/lib/findFirstMatch'>;
}
declare module 'react-router-native-stack/lib/getDimension.js' {
  declare module.exports: $Exports<'react-router-native-stack/lib/getDimension'>;
}
declare module 'react-router-native-stack/lib/getDuration.js' {
  declare module.exports: $Exports<'react-router-native-stack/lib/getDuration'>;
}
declare module 'react-router-native-stack/lib/getEasing.js' {
  declare module.exports: $Exports<'react-router-native-stack/lib/getEasing'>;
}
declare module 'react-router-native-stack/lib/getTransforms.js' {
  declare module.exports: $Exports<'react-router-native-stack/lib/getTransforms'>;
}
declare module 'react-router-native-stack/lib/index.js' {
  declare module.exports: $Exports<'react-router-native-stack/lib/index'>;
}
declare module 'react-router-native-stack/lib/Stack.js' {
  declare module.exports: $Exports<'react-router-native-stack/lib/Stack'>;
}
declare module 'react-router-native-stack/lib/StackTransitioner.js' {
  declare module.exports: $Exports<'react-router-native-stack/lib/StackTransitioner'>;
}
declare module 'react-router-native-stack/lib/styles.js' {
  declare module.exports: $Exports<'react-router-native-stack/lib/styles'>;
}
declare module 'react-router-native-stack/lib/transitionTypes.js' {
  declare module.exports: $Exports<'react-router-native-stack/lib/transitionTypes'>;
}
