// flow-typed signature: 1bff3991f93dfef23ef563fdf3ea2c7e
// flow-typed version: <<STUB>>/redux-promise-middleware_v^4.4.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-promise-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-promise-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-promise-middleware/dist/es/index' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/es/isPromise' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/index' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/isPromise' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/umd/redux-promise-middleware' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/umd/redux-promise-middleware.min' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-promise-middleware/dist/es/index.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/es/index'>;
}
declare module 'redux-promise-middleware/dist/es/isPromise.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/es/isPromise'>;
}
declare module 'redux-promise-middleware/dist/index.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/index'>;
}
declare module 'redux-promise-middleware/dist/isPromise.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/isPromise'>;
}
declare module 'redux-promise-middleware/dist/umd/redux-promise-middleware.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/umd/redux-promise-middleware'>;
}
declare module 'redux-promise-middleware/dist/umd/redux-promise-middleware.min.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/umd/redux-promise-middleware.min'>;
}
declare module 'redux-promise-middleware/webpack.config.js' {
  declare module.exports: $Exports<'redux-promise-middleware/webpack.config'>;
}
