// flow-typed signature: 0d8ca89d48add1c3b2393adbd6d90973
// flow-typed version: <<STUB>>/redux-offline_v^2.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-offline/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/babel-preset-latest_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/eslint-config-formidable_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/eslint-plugin-filenames_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/flow-typed/npm/redux-logger_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/config' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/defaults/batch' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/defaults/detectNetwork' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/defaults/detectNetwork.native' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/defaults/discard' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/defaults/effect' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/defaults/index' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/defaults/persist' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/defaults/persist.native' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/defaults/retry' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/index' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/middleware' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/types' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/updater' {
  declare module.exports: any;
}

declare module 'redux-offline/lib/utils' {
  declare module.exports: any;
}

declare module 'redux-offline/src/actions' {
  declare module.exports: any;
}

declare module 'redux-offline/src/config' {
  declare module.exports: any;
}

declare module 'redux-offline/src/constants' {
  declare module.exports: any;
}

declare module 'redux-offline/src/defaults/batch' {
  declare module.exports: any;
}

declare module 'redux-offline/src/defaults/detectNetwork' {
  declare module.exports: any;
}

declare module 'redux-offline/src/defaults/detectNetwork.native' {
  declare module.exports: any;
}

declare module 'redux-offline/src/defaults/discard' {
  declare module.exports: any;
}

declare module 'redux-offline/src/defaults/effect' {
  declare module.exports: any;
}

declare module 'redux-offline/src/defaults/index' {
  declare module.exports: any;
}

declare module 'redux-offline/src/defaults/persist' {
  declare module.exports: any;
}

declare module 'redux-offline/src/defaults/persist.native' {
  declare module.exports: any;
}

declare module 'redux-offline/src/defaults/retry' {
  declare module.exports: any;
}

declare module 'redux-offline/src/index' {
  declare module.exports: any;
}

declare module 'redux-offline/src/middleware' {
  declare module.exports: any;
}

declare module 'redux-offline/src/types' {
  declare module.exports: any;
}

declare module 'redux-offline/src/updater' {
  declare module.exports: any;
}

declare module 'redux-offline/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-offline/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/babel-preset-latest_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/babel-preset-latest_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/eslint-config-formidable_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/eslint-config-formidable_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/eslint-plugin-filenames_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/eslint-plugin-filenames_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/redux_v3.x.x'>;
}
declare module 'redux-offline/flow-typed/npm/redux-logger_vx.x.x.js' {
  declare module.exports: $Exports<'redux-offline/flow-typed/npm/redux-logger_vx.x.x'>;
}
declare module 'redux-offline/lib/actions.js' {
  declare module.exports: $Exports<'redux-offline/lib/actions'>;
}
declare module 'redux-offline/lib/config.js' {
  declare module.exports: $Exports<'redux-offline/lib/config'>;
}
declare module 'redux-offline/lib/constants.js' {
  declare module.exports: $Exports<'redux-offline/lib/constants'>;
}
declare module 'redux-offline/lib/defaults/batch.js' {
  declare module.exports: $Exports<'redux-offline/lib/defaults/batch'>;
}
declare module 'redux-offline/lib/defaults/detectNetwork.js' {
  declare module.exports: $Exports<'redux-offline/lib/defaults/detectNetwork'>;
}
declare module 'redux-offline/lib/defaults/detectNetwork.native.js' {
  declare module.exports: $Exports<'redux-offline/lib/defaults/detectNetwork.native'>;
}
declare module 'redux-offline/lib/defaults/discard.js' {
  declare module.exports: $Exports<'redux-offline/lib/defaults/discard'>;
}
declare module 'redux-offline/lib/defaults/effect.js' {
  declare module.exports: $Exports<'redux-offline/lib/defaults/effect'>;
}
declare module 'redux-offline/lib/defaults/index.js' {
  declare module.exports: $Exports<'redux-offline/lib/defaults/index'>;
}
declare module 'redux-offline/lib/defaults/persist.js' {
  declare module.exports: $Exports<'redux-offline/lib/defaults/persist'>;
}
declare module 'redux-offline/lib/defaults/persist.native.js' {
  declare module.exports: $Exports<'redux-offline/lib/defaults/persist.native'>;
}
declare module 'redux-offline/lib/defaults/retry.js' {
  declare module.exports: $Exports<'redux-offline/lib/defaults/retry'>;
}
declare module 'redux-offline/lib/index.js' {
  declare module.exports: $Exports<'redux-offline/lib/index'>;
}
declare module 'redux-offline/lib/middleware.js' {
  declare module.exports: $Exports<'redux-offline/lib/middleware'>;
}
declare module 'redux-offline/lib/types.js' {
  declare module.exports: $Exports<'redux-offline/lib/types'>;
}
declare module 'redux-offline/lib/updater.js' {
  declare module.exports: $Exports<'redux-offline/lib/updater'>;
}
declare module 'redux-offline/lib/utils.js' {
  declare module.exports: $Exports<'redux-offline/lib/utils'>;
}
declare module 'redux-offline/src/actions.js' {
  declare module.exports: $Exports<'redux-offline/src/actions'>;
}
declare module 'redux-offline/src/config.js' {
  declare module.exports: $Exports<'redux-offline/src/config'>;
}
declare module 'redux-offline/src/constants.js' {
  declare module.exports: $Exports<'redux-offline/src/constants'>;
}
declare module 'redux-offline/src/defaults/batch.js' {
  declare module.exports: $Exports<'redux-offline/src/defaults/batch'>;
}
declare module 'redux-offline/src/defaults/detectNetwork.js' {
  declare module.exports: $Exports<'redux-offline/src/defaults/detectNetwork'>;
}
declare module 'redux-offline/src/defaults/detectNetwork.native.js' {
  declare module.exports: $Exports<'redux-offline/src/defaults/detectNetwork.native'>;
}
declare module 'redux-offline/src/defaults/discard.js' {
  declare module.exports: $Exports<'redux-offline/src/defaults/discard'>;
}
declare module 'redux-offline/src/defaults/effect.js' {
  declare module.exports: $Exports<'redux-offline/src/defaults/effect'>;
}
declare module 'redux-offline/src/defaults/index.js' {
  declare module.exports: $Exports<'redux-offline/src/defaults/index'>;
}
declare module 'redux-offline/src/defaults/persist.js' {
  declare module.exports: $Exports<'redux-offline/src/defaults/persist'>;
}
declare module 'redux-offline/src/defaults/persist.native.js' {
  declare module.exports: $Exports<'redux-offline/src/defaults/persist.native'>;
}
declare module 'redux-offline/src/defaults/retry.js' {
  declare module.exports: $Exports<'redux-offline/src/defaults/retry'>;
}
declare module 'redux-offline/src/index.js' {
  declare module.exports: $Exports<'redux-offline/src/index'>;
}
declare module 'redux-offline/src/middleware.js' {
  declare module.exports: $Exports<'redux-offline/src/middleware'>;
}
declare module 'redux-offline/src/types.js' {
  declare module.exports: $Exports<'redux-offline/src/types'>;
}
declare module 'redux-offline/src/updater.js' {
  declare module.exports: $Exports<'redux-offline/src/updater'>;
}
declare module 'redux-offline/src/utils.js' {
  declare module.exports: $Exports<'redux-offline/src/utils'>;
}
