// flow-typed signature: 8498da6630d6fa450cd954dda4583226
// flow-typed version: <<STUB>>/remotedev-server_v^0.2.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remotedev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remotedev-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remotedev-server/bin/injectServer' {
  declare module.exports: any;
}

declare module 'remotedev-server/bin/remotedev' {
  declare module.exports: any;
}

declare module 'remotedev-server/lib/adapter' {
  declare module.exports: any;
}

declare module 'remotedev-server/lib/options' {
  declare module.exports: any;
}

declare module 'remotedev-server/lib/store' {
  declare module.exports: any;
}

declare module 'remotedev-server/lib/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remotedev-server/bin/injectServer.js' {
  declare module.exports: $Exports<'remotedev-server/bin/injectServer'>;
}
declare module 'remotedev-server/bin/remotedev.js' {
  declare module.exports: $Exports<'remotedev-server/bin/remotedev'>;
}
declare module 'remotedev-server/index' {
  declare module.exports: $Exports<'remotedev-server'>;
}
declare module 'remotedev-server/index.js' {
  declare module.exports: $Exports<'remotedev-server'>;
}
declare module 'remotedev-server/lib/adapter.js' {
  declare module.exports: $Exports<'remotedev-server/lib/adapter'>;
}
declare module 'remotedev-server/lib/options.js' {
  declare module.exports: $Exports<'remotedev-server/lib/options'>;
}
declare module 'remotedev-server/lib/store.js' {
  declare module.exports: $Exports<'remotedev-server/lib/store'>;
}
declare module 'remotedev-server/lib/worker.js' {
  declare module.exports: $Exports<'remotedev-server/lib/worker'>;
}
