// flow-typed signature: a756950736a337de47d43bb4ccf0de36
// flow-typed version: <<STUB>>/rollbar-browser_v^1.9.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollbar-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollbar-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollbar-browser/browserstack.browsers' {
  declare module.exports: any;
}

declare module 'rollbar-browser/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify' {
  declare module.exports: any;
}

declare module 'rollbar-browser/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter' {
  declare module.exports: any;
}

declare module 'rollbar-browser/defaults' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/plugins/jquery.min' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.min' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.named-amd' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.named-amd.min' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.named-amd.nojson' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.named-amd.nojson.min' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.nojson' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.nojson.min' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.snippet' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.umd' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.umd.min' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.umd.nojson' {
  declare module.exports: any;
}

declare module 'rollbar-browser/dist/rollbar.umd.nojson.min' {
  declare module.exports: any;
}

declare module 'rollbar-browser/examples/browserify/all' {
  declare module.exports: any;
}

declare module 'rollbar-browser/examples/browserify/index' {
  declare module.exports: any;
}

declare module 'rollbar-browser/examples/functions' {
  declare module.exports: any;
}

declare module 'rollbar-browser/examples/webpack/all' {
  declare module.exports: any;
}

declare module 'rollbar-browser/examples/webpack/index' {
  declare module.exports: any;
}

declare module 'rollbar-browser/Gruntfile' {
  declare module.exports: any;
}

declare module 'rollbar-browser/karma.conf' {
  declare module.exports: any;
}

declare module 'rollbar-browser/src/browser' {
  declare module.exports: any;
}

declare module 'rollbar-browser/src/bundles/rollbar' {
  declare module.exports: any;
}

declare module 'rollbar-browser/src/bundles/rollbar.snippet' {
  declare module.exports: any;
}

declare module 'rollbar-browser/src/error_parser' {
  declare module.exports: any;
}

declare module 'rollbar-browser/src/globalnotifier' {
  declare module.exports: any;
}

declare module 'rollbar-browser/src/notifier' {
  declare module.exports: any;
}

declare module 'rollbar-browser/src/plugins/jquery' {
  declare module.exports: any;
}

declare module 'rollbar-browser/src/shim' {
  declare module.exports: any;
}

declare module 'rollbar-browser/src/snippet_callback' {
  declare module.exports: any;
}

declare module 'rollbar-browser/src/util' {
  declare module.exports: any;
}

declare module 'rollbar-browser/src/xhr' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/browserify.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/error_parser.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/express' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/jquery.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/json.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/mootools.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/notifier_ratelimit.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/notifier_retry.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/notifier.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/requirejs-loader' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/requirejs.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/rollbar.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/shim.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/shimalias.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/util.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/test/xhr.test' {
  declare module.exports: any;
}

declare module 'rollbar-browser/vendor/JSON-js/cycle' {
  declare module.exports: any;
}

declare module 'rollbar-browser/vendor/JSON-js/json_parse_state' {
  declare module.exports: any;
}

declare module 'rollbar-browser/vendor/JSON-js/json_parse' {
  declare module.exports: any;
}

declare module 'rollbar-browser/vendor/JSON-js/json' {
  declare module.exports: any;
}

declare module 'rollbar-browser/vendor/JSON-js/json2' {
  declare module.exports: any;
}

declare module 'rollbar-browser/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollbar-browser/browserstack.browsers.js' {
  declare module.exports: $Exports<'rollbar-browser/browserstack.browsers'>;
}
declare module 'rollbar-browser/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify.js' {
  declare module.exports: $Exports<'rollbar-browser/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify'>;
}
declare module 'rollbar-browser/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter.js' {
  declare module.exports: $Exports<'rollbar-browser/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter'>;
}
declare module 'rollbar-browser/defaults.js' {
  declare module.exports: $Exports<'rollbar-browser/defaults'>;
}
declare module 'rollbar-browser/dist/plugins/jquery.min.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/plugins/jquery.min'>;
}
declare module 'rollbar-browser/dist/rollbar.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar'>;
}
declare module 'rollbar-browser/dist/rollbar.min.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.min'>;
}
declare module 'rollbar-browser/dist/rollbar.named-amd.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.named-amd'>;
}
declare module 'rollbar-browser/dist/rollbar.named-amd.min.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.named-amd.min'>;
}
declare module 'rollbar-browser/dist/rollbar.named-amd.nojson.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.named-amd.nojson'>;
}
declare module 'rollbar-browser/dist/rollbar.named-amd.nojson.min.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.named-amd.nojson.min'>;
}
declare module 'rollbar-browser/dist/rollbar.nojson.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.nojson'>;
}
declare module 'rollbar-browser/dist/rollbar.nojson.min.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.nojson.min'>;
}
declare module 'rollbar-browser/dist/rollbar.snippet.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.snippet'>;
}
declare module 'rollbar-browser/dist/rollbar.umd.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.umd'>;
}
declare module 'rollbar-browser/dist/rollbar.umd.min.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.umd.min'>;
}
declare module 'rollbar-browser/dist/rollbar.umd.nojson.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.umd.nojson'>;
}
declare module 'rollbar-browser/dist/rollbar.umd.nojson.min.js' {
  declare module.exports: $Exports<'rollbar-browser/dist/rollbar.umd.nojson.min'>;
}
declare module 'rollbar-browser/examples/browserify/all.js' {
  declare module.exports: $Exports<'rollbar-browser/examples/browserify/all'>;
}
declare module 'rollbar-browser/examples/browserify/index.js' {
  declare module.exports: $Exports<'rollbar-browser/examples/browserify/index'>;
}
declare module 'rollbar-browser/examples/functions.js' {
  declare module.exports: $Exports<'rollbar-browser/examples/functions'>;
}
declare module 'rollbar-browser/examples/webpack/all.js' {
  declare module.exports: $Exports<'rollbar-browser/examples/webpack/all'>;
}
declare module 'rollbar-browser/examples/webpack/index.js' {
  declare module.exports: $Exports<'rollbar-browser/examples/webpack/index'>;
}
declare module 'rollbar-browser/Gruntfile.js' {
  declare module.exports: $Exports<'rollbar-browser/Gruntfile'>;
}
declare module 'rollbar-browser/karma.conf.js' {
  declare module.exports: $Exports<'rollbar-browser/karma.conf'>;
}
declare module 'rollbar-browser/src/browser.js' {
  declare module.exports: $Exports<'rollbar-browser/src/browser'>;
}
declare module 'rollbar-browser/src/bundles/rollbar.js' {
  declare module.exports: $Exports<'rollbar-browser/src/bundles/rollbar'>;
}
declare module 'rollbar-browser/src/bundles/rollbar.snippet.js' {
  declare module.exports: $Exports<'rollbar-browser/src/bundles/rollbar.snippet'>;
}
declare module 'rollbar-browser/src/error_parser.js' {
  declare module.exports: $Exports<'rollbar-browser/src/error_parser'>;
}
declare module 'rollbar-browser/src/globalnotifier.js' {
  declare module.exports: $Exports<'rollbar-browser/src/globalnotifier'>;
}
declare module 'rollbar-browser/src/notifier.js' {
  declare module.exports: $Exports<'rollbar-browser/src/notifier'>;
}
declare module 'rollbar-browser/src/plugins/jquery.js' {
  declare module.exports: $Exports<'rollbar-browser/src/plugins/jquery'>;
}
declare module 'rollbar-browser/src/shim.js' {
  declare module.exports: $Exports<'rollbar-browser/src/shim'>;
}
declare module 'rollbar-browser/src/snippet_callback.js' {
  declare module.exports: $Exports<'rollbar-browser/src/snippet_callback'>;
}
declare module 'rollbar-browser/src/util.js' {
  declare module.exports: $Exports<'rollbar-browser/src/util'>;
}
declare module 'rollbar-browser/src/xhr.js' {
  declare module.exports: $Exports<'rollbar-browser/src/xhr'>;
}
declare module 'rollbar-browser/test/browserify.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/browserify.test'>;
}
declare module 'rollbar-browser/test/error_parser.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/error_parser.test'>;
}
declare module 'rollbar-browser/test/express.js' {
  declare module.exports: $Exports<'rollbar-browser/test/express'>;
}
declare module 'rollbar-browser/test/jquery.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/jquery.test'>;
}
declare module 'rollbar-browser/test/json.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/json.test'>;
}
declare module 'rollbar-browser/test/mootools.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/mootools.test'>;
}
declare module 'rollbar-browser/test/notifier_ratelimit.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/notifier_ratelimit.test'>;
}
declare module 'rollbar-browser/test/notifier_retry.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/notifier_retry.test'>;
}
declare module 'rollbar-browser/test/notifier.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/notifier.test'>;
}
declare module 'rollbar-browser/test/requirejs-loader.js' {
  declare module.exports: $Exports<'rollbar-browser/test/requirejs-loader'>;
}
declare module 'rollbar-browser/test/requirejs.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/requirejs.test'>;
}
declare module 'rollbar-browser/test/rollbar.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/rollbar.test'>;
}
declare module 'rollbar-browser/test/shim.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/shim.test'>;
}
declare module 'rollbar-browser/test/shimalias.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/shimalias.test'>;
}
declare module 'rollbar-browser/test/util.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/util.test'>;
}
declare module 'rollbar-browser/test/xhr.test.js' {
  declare module.exports: $Exports<'rollbar-browser/test/xhr.test'>;
}
declare module 'rollbar-browser/vendor/JSON-js/cycle.js' {
  declare module.exports: $Exports<'rollbar-browser/vendor/JSON-js/cycle'>;
}
declare module 'rollbar-browser/vendor/JSON-js/json_parse_state.js' {
  declare module.exports: $Exports<'rollbar-browser/vendor/JSON-js/json_parse_state'>;
}
declare module 'rollbar-browser/vendor/JSON-js/json_parse.js' {
  declare module.exports: $Exports<'rollbar-browser/vendor/JSON-js/json_parse'>;
}
declare module 'rollbar-browser/vendor/JSON-js/json.js' {
  declare module.exports: $Exports<'rollbar-browser/vendor/JSON-js/json'>;
}
declare module 'rollbar-browser/vendor/JSON-js/json2.js' {
  declare module.exports: $Exports<'rollbar-browser/vendor/JSON-js/json2'>;
}
declare module 'rollbar-browser/webpack.config.js' {
  declare module.exports: $Exports<'rollbar-browser/webpack.config'>;
}
