// flow-typed signature: 00fcf7e3bcd741b365cfe5b3b2566b93
// flow-typed version: <<STUB>>/sanitize.css_v^5.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
