// flow-typed signature: d45e14b8e9860d308ddcd9f6ed29a8df
// flow-typed version: <<STUB>>/sanitize.css_v^5.0.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
