// flow-typed signature: d7860f86d29b1f326f99db4b7d901b9a
// flow-typed version: <<STUB>>/secure-filters_v^1.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'secure-filters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'secure-filters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'secure-filters/lib/secure-filters' {
  declare module.exports: any;
}

declare module 'secure-filters/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'secure-filters/index' {
  declare module.exports: $Exports<'secure-filters'>;
}
declare module 'secure-filters/index.js' {
  declare module.exports: $Exports<'secure-filters'>;
}
declare module 'secure-filters/lib/secure-filters.js' {
  declare module.exports: $Exports<'secure-filters/lib/secure-filters'>;
}
declare module 'secure-filters/test.js' {
  declare module.exports: $Exports<'secure-filters/test'>;
}
