// flow-typed signature: cea506c8d41edffbd8c15f0615f0c9b7
// flow-typed version: <<STUB>>/tachyons-widths_v^5.2.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-widths'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-widths' {
  declare module.exports: any;
}
