// flow-typed signature: e02cd13913c7af167f34a1f7cc868cf2
// flow-typed version: <<STUB>>/tachyons-widths_v^5.2.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-widths'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-widths' {
  declare module.exports: any;
}
