// flow-typed signature: e2288be4e53a7842ee7329e2c0000b06
// flow-typed version: <<STUB>>/tachyons_v^4.1.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons' {
  declare module.exports: any;
}
