// flow-typed signature: 8d5ec809916a2646c974ff2879822f99
// flow-typed version: <<STUB>>/tachyons-vertical-align_v^4.0.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-vertical-align'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-vertical-align' {
  declare module.exports: any;
}
