// flow-typed signature: 22ce99ffcf45c5c79811bfa650ebdd2b
// flow-typed version: <<STUB>>/tachyons-text-align_v^3.0.4/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-text-align'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-text-align' {
  declare module.exports: any;
}
