// flow-typed signature: 12184d6f21d53c78805968c0e46e4c9d
// flow-typed version: <<STUB>>/tachyons-clears_v^3.0.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-clears'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-clears' {
  declare module.exports: any;
}
