// flow-typed signature: f393ce257f19f4c0c0dc8c7d3ff17718
// flow-typed version: <<STUB>>/tachyons-spacing_v^6.0.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-spacing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-spacing' {
  declare module.exports: any;
}
