// flow-typed signature: 3ab28b9e9af30453d58104f8a99746b3
// flow-typed version: <<STUB>>/tachyons-clears_v^3.0.4/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-clears'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-clears' {
  declare module.exports: any;
}
