// flow-typed signature: 83b1f84248466c43752cc433cb1a37d9
// flow-typed version: <<STUB>>/tachyons-vertical-align_v^4.0.4/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-vertical-align'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-vertical-align' {
  declare module.exports: any;
}
