// flow-typed signature: 9c92cee8cb049a4ae96b76c771104f78
// flow-typed version: <<STUB>>/tachyons-text-align_v^3.1.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-text-align'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-text-align' {
  declare module.exports: any;
}
