// flow-typed signature: 9dd7e1acc86e3cc7ae08e9a61f0deb27
// flow-typed version: <<STUB>>/tachyons-position_v^6.0.4/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-position'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-position' {
  declare module.exports: any;
}
