// flow-typed signature: 5339aec8566da68307605b9ee5535e78
// flow-typed version: <<STUB>>/tachyons-flexbox_v^2.0.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-flexbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-flexbox' {
  declare module.exports: any;
}
