// flow-typed signature: 46060aa3cebf94f5b39cc60e4bf37969
// flow-typed version: <<STUB>>/tachyons-display_v^5.0.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-display'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-display' {
  declare module.exports: any;
}
