// flow-typed signature: 3e2eb5b48555d1a1c35b41988095f5b5
// flow-typed version: <<STUB>>/tachyons-position_v^6.0.6/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-position'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-position' {
  declare module.exports: any;
}
