// flow-typed signature: aed1284c781ab407f41248d00252039e
// flow-typed version: <<STUB>>/tachyons-text-align_v^3.1.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-text-align'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-text-align' {
  declare module.exports: any;
}
