// flow-typed signature: ef4649f45582c93d77103bad42cff183
// flow-typed version: <<STUB>>/tachyons-display_v^5.0.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-display'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-display' {
  declare module.exports: any;
}
