// flow-typed signature: 7a0178ca95710c566c6153a12f8b3f76
// flow-typed version: <<STUB>>/transit-immutable-js_v^0.7.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transit-immutable-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'transit-immutable-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'transit-immutable-js/test/handlers' {
  declare module.exports: any;
}

declare module 'transit-immutable-js/test/shared' {
  declare module.exports: any;
}

declare module 'transit-immutable-js/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'transit-immutable-js/index' {
  declare module.exports: $Exports<'transit-immutable-js'>;
}
declare module 'transit-immutable-js/index.js' {
  declare module.exports: $Exports<'transit-immutable-js'>;
}
declare module 'transit-immutable-js/test/handlers.js' {
  declare module.exports: $Exports<'transit-immutable-js/test/handlers'>;
}
declare module 'transit-immutable-js/test/shared.js' {
  declare module.exports: $Exports<'transit-immutable-js/test/shared'>;
}
declare module 'transit-immutable-js/test/test.js' {
  declare module.exports: $Exports<'transit-immutable-js/test/test'>;
}
