// flow-typed signature: 8a7ce40faaf1cfa0f0e18dce5f894417
// flow-typed version: <<STUB>>/transit-js_v^0.8.846/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transit-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'transit-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'transit-js/src/com/cognitect/transit_amd' {
  declare module.exports: any;
}

declare module 'transit-js/src/com/cognitect/transit' {
  declare module.exports: any;
}

declare module 'transit-js/src/com/cognitect/transit/caching' {
  declare module.exports: any;
}

declare module 'transit-js/src/com/cognitect/transit/delimiters' {
  declare module.exports: any;
}

declare module 'transit-js/src/com/cognitect/transit/eq' {
  declare module.exports: any;
}

declare module 'transit-js/src/com/cognitect/transit/handlers' {
  declare module.exports: any;
}

declare module 'transit-js/src/com/cognitect/transit/impl/decoder' {
  declare module.exports: any;
}

declare module 'transit-js/src/com/cognitect/transit/impl/reader' {
  declare module.exports: any;
}

declare module 'transit-js/src/com/cognitect/transit/impl/writer' {
  declare module.exports: any;
}

declare module 'transit-js/src/com/cognitect/transit/types' {
  declare module.exports: any;
}

declare module 'transit-js/src/com/cognitect/transit/util' {
  declare module.exports: any;
}

declare module 'transit-js/transit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'transit-js/src/com/cognitect/transit_amd.js' {
  declare module.exports: $Exports<'transit-js/src/com/cognitect/transit_amd'>;
}
declare module 'transit-js/src/com/cognitect/transit.js' {
  declare module.exports: $Exports<'transit-js/src/com/cognitect/transit'>;
}
declare module 'transit-js/src/com/cognitect/transit/caching.js' {
  declare module.exports: $Exports<'transit-js/src/com/cognitect/transit/caching'>;
}
declare module 'transit-js/src/com/cognitect/transit/delimiters.js' {
  declare module.exports: $Exports<'transit-js/src/com/cognitect/transit/delimiters'>;
}
declare module 'transit-js/src/com/cognitect/transit/eq.js' {
  declare module.exports: $Exports<'transit-js/src/com/cognitect/transit/eq'>;
}
declare module 'transit-js/src/com/cognitect/transit/handlers.js' {
  declare module.exports: $Exports<'transit-js/src/com/cognitect/transit/handlers'>;
}
declare module 'transit-js/src/com/cognitect/transit/impl/decoder.js' {
  declare module.exports: $Exports<'transit-js/src/com/cognitect/transit/impl/decoder'>;
}
declare module 'transit-js/src/com/cognitect/transit/impl/reader.js' {
  declare module.exports: $Exports<'transit-js/src/com/cognitect/transit/impl/reader'>;
}
declare module 'transit-js/src/com/cognitect/transit/impl/writer.js' {
  declare module.exports: $Exports<'transit-js/src/com/cognitect/transit/impl/writer'>;
}
declare module 'transit-js/src/com/cognitect/transit/types.js' {
  declare module.exports: $Exports<'transit-js/src/com/cognitect/transit/types'>;
}
declare module 'transit-js/src/com/cognitect/transit/util.js' {
  declare module.exports: $Exports<'transit-js/src/com/cognitect/transit/util'>;
}
declare module 'transit-js/transit.js' {
  declare module.exports: $Exports<'transit-js/transit'>;
}
