// flow-typed signature: dbe08015c8ea0787690c47b7c9dead3d
// flow-typed version: <<STUB>>/transit-immutable-js_v^0.6.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transit-immutable-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'transit-immutable-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'transit-immutable-js/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'transit-immutable-js/index' {
  declare module.exports: $Exports<'transit-immutable-js'>;
}
declare module 'transit-immutable-js/index.js' {
  declare module.exports: $Exports<'transit-immutable-js'>;
}
declare module 'transit-immutable-js/test/test.js' {
  declare module.exports: $Exports<'transit-immutable-js/test/test'>;
}
