// flow-typed signature: b7b24a5f3a2c6805529a3e9cea1240d2
// flow-typed version: <<STUB>>/urlsearchparams_v^0.1.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'urlsearchparams'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'urlsearchparams' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'urlsearchparams/test/test' {
  declare module.exports: any;
}

declare module 'urlsearchparams/urlsearchparams' {
  declare module.exports: any;
}

// Filename aliases
declare module 'urlsearchparams/test/test.js' {
  declare module.exports: $Exports<'urlsearchparams/test/test'>;
}
declare module 'urlsearchparams/urlsearchparams.js' {
  declare module.exports: $Exports<'urlsearchparams/urlsearchparams'>;
}
