// flow-typed signature: ddd6cc28fbb17c6950568d7575df6b9d
// flow-typed version: <<STUB>>/vision_v^4.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vision'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vision' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vision/examples/cms/pages' {
  declare module.exports: any;
}

declare module 'vision/examples/cms/server' {
  declare module.exports: any;
}

declare module 'vision/examples/ejs/basic' {
  declare module.exports: any;
}

declare module 'vision/examples/ejs/layout' {
  declare module.exports: any;
}

declare module 'vision/examples/handlebars/basic' {
  declare module.exports: any;
}

declare module 'vision/examples/handlebars/helpers' {
  declare module.exports: any;
}

declare module 'vision/examples/handlebars/layout' {
  declare module.exports: any;
}

declare module 'vision/examples/handlebars/partials' {
  declare module.exports: any;
}

declare module 'vision/examples/handlebars/templates/withHelpers/helpers/uppercase' {
  declare module.exports: any;
}

declare module 'vision/examples/jsx/index' {
  declare module.exports: any;
}

declare module 'vision/examples/jsx/templates/about' {
  declare module.exports: any;
}

declare module 'vision/examples/jsx/templates/includes/foot' {
  declare module.exports: any;
}

declare module 'vision/examples/jsx/templates/includes/head' {
  declare module.exports: any;
}

declare module 'vision/examples/jsx/templates/index' {
  declare module.exports: any;
}

declare module 'vision/examples/jsx/templates/layout' {
  declare module.exports: any;
}

declare module 'vision/examples/marko/index' {
  declare module.exports: any;
}

declare module 'vision/examples/mixed/index' {
  declare module.exports: any;
}

declare module 'vision/examples/mustache/basic' {
  declare module.exports: any;
}

declare module 'vision/examples/mustache/layout' {
  declare module.exports: any;
}

declare module 'vision/examples/mustache/partials' {
  declare module.exports: any;
}

declare module 'vision/examples/nunjucks/index' {
  declare module.exports: any;
}

declare module 'vision/examples/pug/index' {
  declare module.exports: any;
}

declare module 'vision/lib/index' {
  declare module.exports: any;
}

declare module 'vision/lib/manager' {
  declare module.exports: any;
}

declare module 'vision/test/index' {
  declare module.exports: any;
}

declare module 'vision/test/manager' {
  declare module.exports: any;
}

declare module 'vision/test/templates/valid/helpers/ignore' {
  declare module.exports: any;
}

declare module 'vision/test/templates/valid/helpers/tools/lowercase' {
  declare module.exports: any;
}

declare module 'vision/test/templates/valid/helpers/uppercase' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vision/examples/cms/pages.js' {
  declare module.exports: $Exports<'vision/examples/cms/pages'>;
}
declare module 'vision/examples/cms/server.js' {
  declare module.exports: $Exports<'vision/examples/cms/server'>;
}
declare module 'vision/examples/ejs/basic.js' {
  declare module.exports: $Exports<'vision/examples/ejs/basic'>;
}
declare module 'vision/examples/ejs/layout.js' {
  declare module.exports: $Exports<'vision/examples/ejs/layout'>;
}
declare module 'vision/examples/handlebars/basic.js' {
  declare module.exports: $Exports<'vision/examples/handlebars/basic'>;
}
declare module 'vision/examples/handlebars/helpers.js' {
  declare module.exports: $Exports<'vision/examples/handlebars/helpers'>;
}
declare module 'vision/examples/handlebars/layout.js' {
  declare module.exports: $Exports<'vision/examples/handlebars/layout'>;
}
declare module 'vision/examples/handlebars/partials.js' {
  declare module.exports: $Exports<'vision/examples/handlebars/partials'>;
}
declare module 'vision/examples/handlebars/templates/withHelpers/helpers/uppercase.js' {
  declare module.exports: $Exports<'vision/examples/handlebars/templates/withHelpers/helpers/uppercase'>;
}
declare module 'vision/examples/jsx/index.js' {
  declare module.exports: $Exports<'vision/examples/jsx/index'>;
}
declare module 'vision/examples/jsx/templates/about.jsx' {
  declare module.exports: $Exports<'vision/examples/jsx/templates/about'>;
}
declare module 'vision/examples/jsx/templates/includes/foot.jsx' {
  declare module.exports: $Exports<'vision/examples/jsx/templates/includes/foot'>;
}
declare module 'vision/examples/jsx/templates/includes/head.jsx' {
  declare module.exports: $Exports<'vision/examples/jsx/templates/includes/head'>;
}
declare module 'vision/examples/jsx/templates/index.jsx' {
  declare module.exports: $Exports<'vision/examples/jsx/templates/index'>;
}
declare module 'vision/examples/jsx/templates/layout.jsx' {
  declare module.exports: $Exports<'vision/examples/jsx/templates/layout'>;
}
declare module 'vision/examples/marko/index.js' {
  declare module.exports: $Exports<'vision/examples/marko/index'>;
}
declare module 'vision/examples/mixed/index.js' {
  declare module.exports: $Exports<'vision/examples/mixed/index'>;
}
declare module 'vision/examples/mustache/basic.js' {
  declare module.exports: $Exports<'vision/examples/mustache/basic'>;
}
declare module 'vision/examples/mustache/layout.js' {
  declare module.exports: $Exports<'vision/examples/mustache/layout'>;
}
declare module 'vision/examples/mustache/partials.js' {
  declare module.exports: $Exports<'vision/examples/mustache/partials'>;
}
declare module 'vision/examples/nunjucks/index.js' {
  declare module.exports: $Exports<'vision/examples/nunjucks/index'>;
}
declare module 'vision/examples/pug/index.js' {
  declare module.exports: $Exports<'vision/examples/pug/index'>;
}
declare module 'vision/lib/index.js' {
  declare module.exports: $Exports<'vision/lib/index'>;
}
declare module 'vision/lib/manager.js' {
  declare module.exports: $Exports<'vision/lib/manager'>;
}
declare module 'vision/test/index.js' {
  declare module.exports: $Exports<'vision/test/index'>;
}
declare module 'vision/test/manager.js' {
  declare module.exports: $Exports<'vision/test/manager'>;
}
declare module 'vision/test/templates/valid/helpers/ignore.js' {
  declare module.exports: $Exports<'vision/test/templates/valid/helpers/ignore'>;
}
declare module 'vision/test/templates/valid/helpers/tools/lowercase.js' {
  declare module.exports: $Exports<'vision/test/templates/valid/helpers/tools/lowercase'>;
}
declare module 'vision/test/templates/valid/helpers/uppercase.js' {
  declare module.exports: $Exports<'vision/test/templates/valid/helpers/uppercase'>;
}
