// flow-typed signature: af4f541d8d084623203dc51148f09539
// flow-typed version: <<STUB>>/webpack-blocks-split-vendor_v^0.2.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-blocks-split-vendor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-blocks-split-vendor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-blocks-split-vendor/dist/index' {
  declare module.exports: any;
}

declare module 'webpack-blocks-split-vendor/dist/types' {
  declare module.exports: any;
}

declare module 'webpack-blocks-split-vendor/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-blocks-split-vendor/dist/index.js' {
  declare module.exports: $Exports<'webpack-blocks-split-vendor/dist/index'>;
}
declare module 'webpack-blocks-split-vendor/dist/types.js' {
  declare module.exports: $Exports<'webpack-blocks-split-vendor/dist/types'>;
}
declare module 'webpack-blocks-split-vendor/dist/utils.js' {
  declare module.exports: $Exports<'webpack-blocks-split-vendor/dist/utils'>;
}
declare module 'webpack-blocks-split-vendor/index' {
  declare module.exports: $Exports<'webpack-blocks-split-vendor'>;
}
declare module 'webpack-blocks-split-vendor/index.js' {
  declare module.exports: $Exports<'webpack-blocks-split-vendor'>;
}
