// flow-typed signature: eff13e157a298a64522d01d9d7f78ba8
// flow-typed version: <<STUB>>/webpack-chunk-hash_v^0.4.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-chunk-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-chunk-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-chunk-hash/index' {
  declare module.exports: $Exports<'webpack-chunk-hash'>;
}
declare module 'webpack-chunk-hash/index.js' {
  declare module.exports: $Exports<'webpack-chunk-hash'>;
}
