# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'reactTemplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for reactTemplate
  pod 'Firebase/Core'
  pod 'Firebase/Crash'

  # target 'reactTemplate-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'reactTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'reactTemplate-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for reactTemplate-tvOS

#   target 'reactTemplate-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
